refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    filters:
      - kind: threshold
        level: warn
  rolling_file:
    kind: rolling_file
    path: "log/output.log"
    policy:
      trigger:
        kind: time
        interval: 5 days
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "log/output.{}.log"

root:
  level: info
  appenders:
    - rolling_file
    - stdout